import React from 'react';

export default function Terms() {
  return (
    <div className="editorial-container">
      <div className="editorial-header">
        <h1 className="editorial-title">Terms of Service</h1>
        <p className="editorial-subtitle">
          Last updated: June 14, 2026. Please read these Terms of Service carefully before using the CodeMetrics platform.
        </p>
      </div>

      <div className="editorial-body">
        <section className="editorial-section">
          <h2 className="editorial-h2">1. Acceptance of Terms</h2>
          <p className="editorial-p">
            By accessing or using CodeMetrics, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
        </section>

        <section className="editorial-section">
          <h2 className="editorial-h2">2. Description of Service</h2>
          <p className="editorial-p">
            CodeMetrics provides developer analytics, repository insights, profile completeness scoring, and career readiness estimations by fetching public GitHub metadata. We reserve the right to modify, suspend, or discontinue any aspect of the service at any time without prior notice.
          </p>
        </section>

        <section className="editorial-section">
          <h2 className="editorial-h2">3. User Accounts & Security</h2>
          <p className="editorial-p">
            To access certain features of the platform, you may be required to sign in using your GitHub account via OAuth. You are responsible for maintaining the confidentiality of your session credentials and for all activities that occur under your account.
          </p>
        </section>

        <section className="editorial-section">
          <h2 className="editorial-h2">4. Acceptable Use Policy</h2>
          <p className="editorial-p">
            You agree not to use CodeMetrics to:
          </p>
          <ul className="editorial-list">
            <li className="editorial-list-item">Violate any local, state, national, or international laws.</li>
            <li className="editorial-list-item">Attempt to bypass API rate limits, scrape the platform, or disrupt service integrity.</li>
            <li className="editorial-list-item">Reverse engineer, decompile, or extract the underlying source code of the platform.</li>
          </ul>
        </section>

        <section className="editorial-section">
          <h2 className="editorial-h2">5. Disclaimer of Warranties</h2>
          <p className="editorial-p">
            CodeMetrics is provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, regarding the accuracy, completeness, reliability, or availability of the analytics, insights, or career recommendations generated by the platform.
          </p>
        </section>

        <section className="editorial-section">
          <h2 className="editorial-h2">6. Limitation of Liability</h2>
          <p className="editorial-p">
            In no event shall CodeMetrics, its creators, or partners be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the platform.
          </p>
        </section>

        <section className="editorial-section">
          <h2 className="editorial-h2">7. Changes to Terms</h2>
          <p className="editorial-p">
            We reserve the right to revise these Terms of Service at any time. By continuing to use the platform after modifications are posted, you agree to be bound by the updated terms.
          </p>
        </section>
      </div>
    </div>
  );
}
